
###########################NETWORKS###########################
networks:
  socket_proxy:
    name: socket_proxy
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 172.21.0.0/24
  external:
    name: "external"
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
    enable_ipv4: true
    enable_ipv6: true
  internal: # No internet access
    name: "internal"
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 172.19.0.0/16
    enable_ipv4: true
    enable_ipv6: false

###########################SECRETS###########################
secrets:
  smtp_password:
    file: $DOCKERDIR/secrets/smtp/password
  cf_dns_api_token:
    file: $DOCKERDIR/secrets/cloudflare/dns_api_token
  cf_tunnel_token:
    file: $DOCKERDIR/secrets/cloudflare/tunnel_token
  postgres_password:
    file: $DOCKERDIR/secrets/postgres/password

  #AUHELIA####################################################
  authelia_jwt:
    file: $DOCKERDIR/secrets/authelia/jwt
  authelia_secret_key:
    file: $DOCKERDIR/secrets/authelia/secret_key
  authelia_pg_password:
    file: $DOCKERDIR/secrets/authelia/pg_password
  authelia_encryption:
    file: $DOCKERDIR/secrets/authelia/encryption
  authelia_hmac_secret:
    file: $DOCKERDIR/secrets/authelia/hmac_secret
  authelia_jwks:
    file: $DOCKERDIR/secrets/authelia/jwks
  #AUTHENTIK####################################################
  authentik_secret_key:
    file: $DOCKERDIR/secrets/authentik/secret_key
  authentik_pg_password:
    file: $DOCKERDIR/secrets/authentik/pg_password
  #FILEBROWSER####################################################
  filebrowser_oidc_client_id:
    file: $DOCKERDIR/secrets/filebrowser/oidc_clientid
  filebrowser_oidc_client_secret:
    file: $DOCKERDIR/secrets/filebrowser/oidc_secret
  #FRESHRSS####################################################
  freshrss_oidc_clientid:
    file: $DOCKERDIR/secrets/freshrss/oidc_clientid
  freshrss_oidc_secret:
    file: $DOCKERDIR/secrets/freshrss/oidc_secret
  freshrss_pg_password:
    file: $DOCKERDIR/secrets/freshrss/pg_password
  #GRIMMORY####################################################  
  grimmory_db_password:
    file: $DOCKERDIR/secrets/grimmory/db_password
  grimmory_mdb_password:
    file: $DOCKERDIR/secrets/grimmory/mdb_password
  #home-assistant####################################################
  homeassis_oidc_clientid:
    file: $DOCKERDIR/secrets/homeassis/oidc_clientid 
  homeassis_oidc_secret:
    file: $DOCKERDIR/secrets/homeassis/oidc_secret
  #immich###########################################################
  immich_oidc_clientid:
    file: $DOCKERDIR/secrets/immich/oidc_clientid
  immich_oidc_secret:
    file: $DOCKERDIR/secrets/immich/oidc_secret
  immich_pg_password:
    file: $DOCKERDIR/secrets/immich/pg_password
  #LINKWARDEN#################################################### 
  linkwarden_oidc_clientid:
    file: $DOCKERDIR/secrets/linkwarden/oidc_clientid
  linkwarden_oidc_secret:
    file: $DOCKERDIR/secrets/linkwarden/oidc_secret
  linkwarden_pg_password:
    file: $DOCKERDIR/secrets/linkwarden/pg_password
  linkwarden_nextauth_secret:
    file: $DOCKERDIR/secrets/linkwarden/nextauth_secret
#LLDAP#################################################### 
  lldap_jwt_secret:
    file: $DOCKERDIR/secrets/lldap/jwt_secret
  lldap_key_seed:
    file: $DOCKERDIR/secrets/lldap/key_seed
  lldap_user_pass:
    file: $DOCKERDIR/secrets/lldap/user_pass
  lldap_database_url:
    file: $DOCKERDIR/secrets/lldap/database_url
#MEALIE####################################################
  mealie_oidc_clientid:
    file: $DOCKERDIR/secrets/mealie/oidc_clientid
  mealie_oidc_secret:
    file: $DOCKERDIR/secrets/mealie/oidc_secret
  mealie_pg_password:
    file: $DOCKERDIR/secrets/mealie/pg_password
#VAULTWARDEN####################################################
  vaultwarden_pg_url:
    file: $DOCKERDIR/secrets/vaultwarden/pg_url
  vaultwarden_oidc_clientid:
    file: $DOCKERDIR/secrets/vaultwarden/oidc_clientid
  vaultwarden_oidc_clientsecret:
    file: $DOCKERDIR/secrets/vaultwarden/oidc_clientsecret
  vaultwarden_push_id:
    file: $DOCKERDIR/secrets/vaultwarden/push_id
  vaultwarden_push_key:
    file: $DOCKERDIR/secrets/vaultwarden/push_key
  vaultwarden_admin_token:
    file: $DOCKERDIR/secrets/vaultwarden/admin_token
 #WIREGUARD####################################################
  wireguard_private_key:
    file: $DOCKERDIR/secrets/wireguard/private_key
  wireguard_preshared_key: 
    file: $DOCKERDIR/secrets/wireguard/preshared_key
  wireguard_addresses: 
    file: $DOCKERDIR/secrets/wireguard/addresses
###########################SERVICES###########################
include:
    #core
    - compose/cloudflared/cloudflared.yaml
    - compose/traefik/traefik.yaml   
    - compose/authelia/authelia.yaml 
    - compose/lldap/lldap.yaml
    #- compose/auth/authentik.yaml
    - compose/vpn/gluetun.yaml   
    - compose/dozzle/dozzle.yaml 
    - compose/deunhealth/deunhealth.yaml
    - compose/watchtower/watchtower.yaml
    - compose/postgresql/postgresql.yaml
    - compose/pg-admin/pg-admin.yaml
    - compose/redis/redis.yaml
    - compose/socket-proxy/socket-proxy.yaml
    
    #arrstack
    - compose/audiobookshelf/audiobookshelf.yaml
    - compose/grimmory/grimmory.yaml    
    - compose/chaptarr/chaptarr.yaml
    - compose/prowlarr/prowlarr.yaml
    - compose/qbittorrent/qbittorrent.yaml
    - compose/mousehole/mousehole.yaml
    #- compose/bookkeep/bookkeep.yaml

    #data
    - compose/filebrowser/filebrowser.yaml 

    #organization
    - compose/mealie/mealie.yaml
    - compose/couch-db/couch-db.yaml
    - compose/radicale/radicale.yaml
    #- compose/linkwarden/linkwarden.yaml
    #- compose/leantime/leantime.yaml

    #storage 
    - compose/immich/immich.yaml   
    - compose/vaultwarden/vaultwarden.yaml
    - compose/home-assistant/home-assistant.yaml

    #other
    - compose/irc/thelounge.yaml
    - compose/fresh-rss/fresh-rss.yaml  