# NOTE (OCTOBER 15, 2025): At this time, my Synology setup has not been updated to UDMS 2025/Deployrr standards. It still follows my old way of doing things. 

########################### NETWORKS
# You may customize the network subnets (192.168.x.0/24) below as you please.
networks:
  default:
    driver: bridge
  socket_proxy:
    name: socket_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/24
  external:
    name: "external"
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
    enable_ipv4: true
    enable_ipv6: true
  internal: # No internet access
    name: "internal"
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 172.19.0.0/16
    enable_ipv4: true
    enable_ipv6: false

########################### SECRETS
secrets:
  cf_dns_api_token:
    file: $DOCKERDIR/secrets/cf_dns_api_token
  cf_tunnel_token:
    file: $DOCKERDIR/secrets/cf_tunnel_token
  authentik_secret_key:
    file: $DOCKERDIR/secrets/authentik_secret_key
  postgres_password:
    file: $DOCKERDIR/secrets/postgres_password




# Docker Compose v2.20 or greater required to use "include"
include:
  ########################### SERVICES
    #- compose/postgresql/compose.yaml

    # - compose/traefik/compose.yaml
    # - compose/cloudflared/compose.yaml
    # - compose/auth/compose.yaml    
    # #socket proxy
    # #arrstack
    # - compose/audiobookshelf/compose.yaml
    # - compose/booklore/compose.yaml
    # - compose/chaptarr/compose.yaml
    # - compose/prowlarr/compose.yaml
    # - compose/qbittorrent/compose.yaml

    # # #apps
    # - compose/cloudreve/compose.yaml
    # - compose/couch-db/compose.yaml
    # - compose/fresh-rss/compose.yaml
    # - compose/home-assistant/compose.yaml
    # - compose/immich/compose.yaml
    # - compose/irc/compose.yaml
    # #- compose/leantime/compose.yaml
    # - compose/linkwarden/compose.yaml
    # - compose/mealie/compose.yaml
    # - compose/radicale/compose.yaml
    - compose/vaultwarden/compose.yaml








  # # CORE
  # - compose/$HOSTNAME/traefik.yml
  # - compose/$HOSTNAME/socket-proxy.yml
  # - compose/$HOSTNAME/oauth.yml
  # - compose/$HOSTNAME/portainer.yml
  # # NETWORK
  # - compose/$HOSTNAME/zerotier.yml
  # # - compose/$HOSTNAME/adguardhome.yml
  # # MEDIA

  # # FILE MANAGEMENT
  # # - compose/$HOSTNAME/rclone-gdrive.yml
  # # - compose/$HOSTNAME/rclone-gcrypt.yml
  # # - compose/$HOSTNAME/mergerfs.yml
  # - compose/$HOSTNAME/syncthing.yml
  # - compose/$HOSTNAME/vscode.yml
  # # MONITORING
  # - compose/$HOSTNAME/glances.yml
  # # - compose/$HOSTNAME/qdirstat.yml
  # # MAINTENANCE
  # - compose/$HOSTNAME/docker-gc.yml
  # - compose/$HOSTNAME/ddns-updater.yml
  # # - compose/$HOSTNAME/certdumper.yml