
###########################NETWORKS###########################
networks:
  socket_proxy:
    name: socket_proxy
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 172.21.0.0/24
  external:
    name: "external"
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
    enable_ipv4: true
    enable_ipv6: true
  internal: # No internet access
    name: "internal"
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 172.19.0.0/16
    enable_ipv4: true
    enable_ipv6: false

###########################SECRETS###########################
secrets:
  smtp_password:
    file: $DOCKERDIR/secrets/smtp_password
  cf_dns_api_token:
    file: $DOCKERDIR/secrets/cf_dns_api_token
  cf_tunnel_token:
    file: $DOCKERDIR/secrets/cf_tunnel_token
  postgres_password:
    file: $DOCKERDIR/secrets/postgres_password
  ###########################################################
  authentik_secret_key:
    file: $DOCKERDIR/secrets/authentik_secret_key
  authentik_pg_password:
    file: $DOCKERDIR/secrets/authentik_pg_password
  ###########################################################  
  booklore_db_password:
    file: $DOCKERDIR/secrets/booklore_db_password
  booklore_mdb_password:
    file: $DOCKERDIR/secrets/booklore_mdb_password
  ###########################################################  
  freshrss_oidc_clientid:
    file: $DOCKERDIR/secrets/freshrss_oidc_clientid
  freshrss_oidc_secret:
    file: $DOCKERDIR/secrets/freshrss_oidc_secret
  freshrss_pg_password:
    file: $DOCKERDIR/secrets/freshrss_pg_password
  ###########################################################
  homeassis_oidc_clientid:
    file: $DOCKERDIR/secrets/homeassis_oidc_clientid 
  homeassis_oidc_secret:
    file: $DOCKERDIR/secrets/homeassis_oidc_secret
  ###########################################################
  immich_oidc_clientid:
    file: $DOCKERDIR/secrets/immich_oidc_clientid
  immich_oidc_secret:
    file: $DOCKERDIR/secrets/immich_oidc_secret
  immich_pg_password:
    file: $DOCKERDIR/secrets/immich_pg_password
  ###########################################################
  linkwarden_oidc_clientid:
    file: $DOCKERDIR/secrets/linkwarden_oidc_clientid
  linkwarden_oidc_secret:
    file: $DOCKERDIR/secrets/linkwarden_oidc_secret
  linkwarden_pg_password:
    file: $DOCKERDIR/secrets/linkwarden_pg_password
  linkwarden_nextauth_secret:
    file: $DOCKERDIR/secrets/linkwarden_nextauth_secret
  ###########################################################
  mealie_oidc_clientid:
    file: $DOCKERDIR/secrets/mealie_oidc_clientid
  mealie_oidc_secret:
    file: $DOCKERDIR/secrets/mealie_oidc_secret
  mealie_pg_password:
    file: $DOCKERDIR/secrets/mealie_pg_password
  ###########################################################
  vaultwarden_pg_url:
    file: $DOCKERDIR/secrets/vaultwarden_pg_url
  vaultwarden_oidc_clientid:
    file: $DOCKERDIR/secrets/vaultwarden_oidc_clientid
  vaultwarden_oidc_clientsecret:
    file: $DOCKERDIR/secrets/vaultwarden_oidc_clientsecret
  vaultwarden_push_id:
    file: $DOCKERDIR/secrets/vaultwarden_push_id
  vaultwarden_push_key:
    file: $DOCKERDIR/secrets/vaultwarden_push_key
  vaultwarden_admin_token:
    file: $DOCKERDIR/secrets/vaultwarden_admin_token
  ############################################################
  wireguard_private_key:
    file: $DOCKERDIR/secrets/wireguard_private_key



# Docker Compose v2.20 or greater required to use "include"
include:
  ###########################SERVICES###########################
    - compose/traefik/compose.yaml
    - compose/cloudflared/compose.yaml
    - compose/auth/compose.yaml
    - compose/vpn/compose.yaml
    - compose/socket-proxy/compose.yaml
    
    - compose/postgresql/compose.yaml

    - compose/dozzle/compose.yaml
    - compose/deunhealth/compose.yaml
    - compose/watchtower/compose.yaml
    # #arrstack
    - compose/audiobookshelf/compose.yaml
    - compose/booklore/compose.yaml    
    - compose/chaptarr/compose.yaml
    - compose/prowlarr/compose.yaml
    - compose/qbittorrent/compose.yaml
    - compose/bookkeep/compose.yaml
    #- compose/qui/compose.yaml

    # # #apps
    #- compose/cloudreve/compose.yaml
    #- compose/copyparty/compose.yaml
    #- compose/filestash/compose.yaml
    #- compose/filebrowser/compose.yaml
    
    - compose/couch-db/compose.yaml
    - compose/fresh-rss/compose.yaml    
    - compose/home-assistant/compose.yaml
    - compose/immich/compose.yaml    
    - compose/irc/compose.yaml
    #- compose/leantime/compose.yaml
    #- compose/linkwarden/compose.yaml
    - compose/mealie/compose.yaml
    - compose/radicale/compose.yaml
    - compose/vaultwarden/compose.yaml








  # # CORE
  # - compose/$HOSTNAME/traefik.yml
  # - compose/$HOSTNAME/socket-proxy.yml
  # - compose/$HOSTNAME/oauth.yml
  # - compose/$HOSTNAME/portainer.yml
  # # NETWORK
  # - compose/$HOSTNAME/zerotier.yml
  # # - compose/$HOSTNAME/adguardhome.yml
  # # MEDIA

  # # FILE MANAGEMENT
  # # - compose/$HOSTNAME/rclone-gdrive.yml
  # # - compose/$HOSTNAME/rclone-gcrypt.yml
  # # - compose/$HOSTNAME/mergerfs.yml
  # - compose/$HOSTNAME/syncthing.yml
  # - compose/$HOSTNAME/vscode.yml
  # # MONITORING
  # - compose/$HOSTNAME/glances.yml
  # # - compose/$HOSTNAME/qdirstat.yml
  # # MAINTENANCE
  # - compose/$HOSTNAME/docker-gc.yml
  # - compose/$HOSTNAME/ddns-updater.yml
  # # - compose/$HOSTNAME/certdumper.yml