services:
  chaptarr:
    container_name: chaptarr
    image: ${CHAPTARR__IMAGE}:${CHAPTARR__VERSION}
    restart: unless-stopped
    depends_on:
      traefik:
        condition: service_started
        restart: false
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
    environment:
      TZ: ${TZ}   
      PUID: ${PUID}
      PGID: ${PGID}
      Chaptarr__Postgres__Host: ${POSTGRESQL__HOST}
      Chaptarr__Postgres__User: ${CHAPTARR__DB_USER}
      Chaptarr__Postgres__Password: ${CHAPTARR__DB_PASSWORD}
      Chaptarr__Postgres__Port: ${CHAPTARR__DB_PORT}      
    networks:
      - external
      - internal
    labels:
      - "traefik.enable=true"       
      - "traefik.http.routers.chaptarr.rule=Host(`chaptarr.${DOMAINNAME}`)"   
      - "traefik.http.routers.chaptarr.middlewares=authelia@docker"     
      - "traefik.http.services.chaptarr.loadbalancer.server.port=8789"
      - "deunhealth.restart.on.unhealthy=true"
    volumes:
      - ${VOLDIR}/chaptarr:/config
      - ${DATADIR}/torrents/books:/ebooks
      - ${DATADIR}/torrents/downloads:/downloads