services:
  chaptarr:
    container_name: chaptarr
    image: robertlordhood/chaptarr:develop
    volumes:
      - ${VOLDIR}/chaptarr:/config
      - ${DATADIR}/torrents/books:/ebooks
      - ${DATADIR}/torrents/downloads:/downloads
    restart: unless-stopped  
    networks:
      - internal
    labels:
      - "traefik.enable=true"       
      - "traefik.http.routers.chaptarr.rule=Host(`chaptarr.int.$DOMAINNAME`)"      
      - "traefik.http.services.chaptarr.loadbalancer.server.port=8789"      



  # unpackerr:
  #   image: golift/unpackerr
  #   container_name: unpackerr
  #   volumes:
  #     - ${TORRENT_DIRECTORY}/downloads:/downloads
  #   restart: always
  #   env_file:
  #     - .env