services:
  chaptarr:
    container_name: chaptarr
    image: robertlordhood/chaptarr:develop
    restart: unless-stopped
    depends_on:
      traefik:
        condition: service_started
        restart: false
    logging:
      options:
        max-size: 10m
    networks:
      - external
    labels:
      - "traefik.enable=true"       
      - "traefik.http.routers.chaptarr.rule=Host(`chaptarr.int.${DOMAINNAME}`)"      
      - "traefik.http.services.chaptarr.loadbalancer.server.port=8789"
      
      - "deunhealth.restart.on.unhealthy=true"
    volumes:
      - ${VOLDIR}/chaptarr:/config
      - ${DATADIR}/torrents/books:/ebooks
      - ${DATADIR}/torrents/downloads:/downloads