services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie
    container_name: mealie
    restart: always
    volumes:
      - ${VOLDIR}/mealie/:/app/data/
    env_file: .env
    networks:
      - external
      - internal
    labels:
      - "traefik.enable=true"       
      - "traefik.http.routers.mealie.rule=Host(`mealie.$DOMAINNAME`)"      
      - "traefik.http.services.mealie.loadbalancer.server.port=9000"