services:
  grimmory:
    image: ${GRIMMORY__IMAGE}:${GRIMMORY__VERSION}
    container_name: ${GRIMMORY__NAME}
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
      - apparmor:unconfined
    cap_drop:
      - ALL
    cap_add:
      # - CHOWN
      - SETGID
      - SETUID
    tmpfs:
      - /tmp:rw,noexec,nosuid
    depends_on:
      traefik:
        condition: service_started
        restart: false
      mariadb:
        condition: service_started
        restart: false
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - LOG_LEVEL=${LOG_LEVEL}
      - DATABASE_URL=${GRIMMORY__DB_URL}
      - DATABASE_USERNAME=${GRIMMORY__DB_USER}
      - DATABASE_PASSWORD=${GRIMMORY__DB_PASSWORD}
      - GRIMMORY_PORT=${GRIMMORY__PORT}   
    volumes:
      - ${VOLDIR}/${GRIMMORY__NAME}/data:/app/data:rw
      - ${DATADIR}/torrents/:/books:rw
      - ${DATADIR}/downloads/:/bookdrop:rw
    networks:
      - external
      - internal
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${GRIMMORY__NAME}.rule=Host(`${GRIMMORY__NAME}.$DOMAINNAME`)"      
      - "traefik.http.routers.${GRIMMORY__NAME}.middlewares=authelia@docker"  
      - "traefik.http.services.${GRIMMORY__NAME}.loadbalancer.server.port=${GRIMMORY__PORT}"
      - "deunhealth.restart.on.unhealthy=true"
  
  mariadb:
    container_name: grimmory-mariadb
    image: ${MARIADB__IMAGE}:${MARIADB__VERSION}
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
      - apparmor:unconfined
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    #read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - LOG_LEVEL=${LOG_LEVEL}
      - MYSQL_USER=${GRIMMORY__DB_USER}
      - MYSQL_DATABASE=${GRIMMORY__DB_NAME}
      - MYSQL_PASSWORD=${GRIMMORY__DB_PASSWORD}      
      - MYSQL_ROOT_PASSWORD=${GRIMMORY__ROOT_PASSWORD}   
    volumes:
      - ${VOLDIR}/${GRIMMORY__NAME}/mariadb/:/config:rw
    networks:
      - internal
    labels:      
      - "deunhealth.restart.on.unhealthy=true"