services:
  grimmory:
    image: ${GRIMMORY__IMAGE}:${GRIMMORY__VERSION}
    container_name: grimmory
    restart: unless-stopped
    depends_on:
      traefik:
        condition: service_started
        restart: false
      mariadb:
        condition: service_started
        restart: false
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
    environment:
      - UMASK="000"
      - TZ="${TZ}"
      - PUID="${PUID}"
      - PGID="${PGID}"      
      - DATABASE_URL=${GRIMMORY__DB_URL}
      - DATABASE_USERNAME=${GRIMMORY__DB_USER}
      - DATABASE_PASSWORD=${GRIMMORY__DB_PASSWORD}
      - GRIMMORY_PORT=${GRIMMORY__PORT}   
    volumes:
      - ${VOLDIR}/grimmory/data:/app/data
      - ${DATADIR}/torrents/:/books
      - ${VOLDIR}/grimmory/:/bookdrop
    networks:
      - external
      - internal
    labels:
      - "traefik.enable=true"       
      - "traefik.http.routers.grimmory.rule=Host(`grimmory.$DOMAINNAME`)"      
      - "traefik.http.routers.grimmory.middlewares=authelia@docker"  
      - "traefik.http.services.grimmory.loadbalancer.server.port=${GRIMMORY__PORT}"
      - "deunhealth.restart.on.unhealthy=true"
  
  mariadb:
    container_name: grimmory-mariadb
    image: ${MARIADB__IMAGE}:${MARIADB__VERSION}
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - MYSQL_USER=${GRIMMORY__DB_USER}
      - MYSQL_DATABASE=${GRIMMORY__DB_NAME}
      - MYSQL_PASSWORD=${GRIMMORY__DB_PASSWORD}      
      - MYSQL_ROOT_PASSWORD=${GRIMMORY__ROOT_PASSWORD}   
    volumes:
      - ${VOLDIR}/grimmory/mariadb/:/config
    networks:
      - internal
    labels:      
      - "deunhealth.restart.on.unhealthy=true"