services:
  tunnel:
    container_name: cloudflared
    image: cloudflare/cloudflared
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
    command: tunnel run
    secrets:
      - cf_tunnel_token
    networks:
      - external
    environment:
      - TUNNEL_TOKEN_FILE=/run/secrets/cf_tunnel_token 
      - "deunhealth.restart.on.unhealthy=true"
      - "com.centurylinklabs.watchtower.monitor-only=true"
