services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    env_file: .env
    networks:
      - external
    #network_mode: host
    ports:
      - 8123:8123
    volumes:
      - ${VOLDIR}/home-assistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    labels:
      - "traefik.enable=true"       
      - "traefik.http.routers.homeassistant.rule=Host(`ha.$DOMAINNAME`)"      
      - "traefik.http.services.homeassistant.loadbalancer.server.port=8123"

networks:
   external:
     name: external
     external: true

#netowrks: {}