services:
  homeassistant:
    container_name: homeassistant
    image: ${HOMEASSISTANT__IMAGE}:${HOMEASSISTANT__VERSION}
    restart: unless-stopped
    depends_on:
      traefik:
        condition: service_started
        restart: false
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
    networks:
      - external
    labels:
      - "traefik.enable=true"       
      - "traefik.http.routers.homeassistant.rule=Host(`ha.$DOMAINNAME`)"     
      #- "traefik.http.routers.homeassistant.middlewares=authelia@docker"   
      - "traefik.http.services.homeassistant.loadbalancer.server.port=8123"
      - "deunhealth.restart.on.unhealthy=true"
    volumes:
      - ${VOLDIR}/home-assistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro