services:
  irc:
    container_name: thelounge
    image: ${IRC__IMAGE}:${IRC__VERSION}
    restart: always
    security_opt:
    - no-new-privileges:true
    - apparmor:unconfined
    cap_drop:
    - ALL
    cap_add:
    #- chown
    - SETGID
    - SETUID
    #read_only: true
    tmpfs:
    - /tmp:rw,noexec,nosuid
    depends_on:
      traefik:
        condition: service_started
        restart: false
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
    networks:
    - external
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.irc.rule=Host(`irc.int.$DOMAINNAME`)"
    - "traefik.http.routers.irc.middlewares=authelia@docker"
    - "traefik.http.services.irc.loadbalancer.server.port=9000"
    - "deunhealth.restart.on.unhealthy=true"
    volumes:
    - ${VOLDIR}/irc/:/var/opt/thelounge
