services:
  socket-proxy:
    container_name: socket-proxy
    image: ${SOCKET_PROXY_IMAGE:-lscr.io/linuxserver/socket-proxy}:${SOCKET_PROXY_IMAGE_TAG:-latest}
    #profiles: ["${SOCKET_PROXY_PROFILE:-infrastructure}"]
    restart: unless-stopped
    networks:
      - socket_proxy
    read_only: true
    environment:
      TZ: "${TZ:-Europe/London}"
      LOG_LEVEL: "notice" # debug, info, notice, warning, err, crit, alert, emerg
      DISABLE_IPV6: "0"
      ALLOW_START: "1"
      ALLOW_STOP: "1"
      ALLOW_RESTARTS: "1"
      AUTH: "0"
      BUILD: "0"
      COMMIT: "0"
      CONFIGS: "0"
      CONTAINERS: "1"
      DISTRIBUTION: "0"
      EVENTS: "1"
      EXEC: "0"
      IMAGES: "1"
      INFO: "1"
      NETWORKS: "1"
      NODES: "0"
      PING: "1"
      PLUGINS: "0"
      POST: "1"
      SECRETS: "0"
      SERVICES: "1"
      SESSION: "0"
      SWARM: "0"
      SYSTEM: "0"
      TASKS: "0"
      VERSION: "1"
      VOLUMES: "1"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    tmpfs:
      - "/run"
    labels:
      - "traefik.enable=false"
    healthcheck:
      interval: "30s"
      timeout: "5s"
      retries: 3
      start_period: "10s"
      test: "wget --no-verbose --tries=1 --spider http://localhost:2375/_ping || exit 1"