services:
  bookkeep:
    container_name: bookkeep
    image: akiraslingshot/bookkeep
    restart: unless-stopped
    depends_on:
      traefik:
        condition: service_started
        restart: false
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
    networks:
      - external
      - internal
    environment:
      TZ: "${TZ}"
      PUID: "${PUID}"
      PGID: "${PGID}"
      HARDCOVER_API_TOKEN: "${BOOKKEEP__HARDCOVER_API_TOKEN}"
      BOOKKEEP_SECRET_KEY: "${BOOKKEEP__SECRET_KEY}"
      DATABASE_URL: "${BOOKKEEP__DATABASE_URL}"
      REDIS_URL: "${REDIS__URL}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bookkeep-https.rule=Host(`bookkeep.$DOMAINNAME`)"
      - "traefik.http.routers.bookkeep.middlewares=authelia@docker"
      - "traefik.http.services.bookkeep.loadbalancer.server.port=8000"      
      - "deunhealth.restart.on.unhealthy=true"
    volumes:      
      - ${DATADIR}/torrents/books:/ebooks
      - ${DATADIR}/torrents/downloads:/downloads   
    