services:
  bookkeep:
    container_name: bookkeep
    image: akiraslingshot/bookkeep
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
    networks:
      - external
      - internal
    env_file:
      - .env
    environment:
      HARDCOVER_API_TOKEN: ${HARDCOVER_API_TOKEN}
      REDIS_URL: ${REDIS__URL}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bookkeep-https.rule=Host(`bookkeep.$DOMAINNAME`)"
      - "traefik.http.services.bookkeep.loadbalancer.server.port=8000"
      
      - "deunhealth.restart.on.unhealthy=true"
    volumes:      
      - ${DATADIR}/torrents/books:/ebooks
      - ${DATADIR}/torrents/downloads:/downloads   
    