services:
  filebrowser:
    container_name: filebrowser
    image: ${FILEBROWSER__IMAGE}:${FILEBROWSER__VERSION}
    restart: unless-stopped
    depends_on:
      traefik:
        condition: service_started
        restart: false
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
    secrets:
      - filebrowser_oidc_client_id
      - filebrowser_oidc_client_secret
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}      
      - FILEBROWSER_DATABASE=${FILEBROWSER__DATABASE}
      - FILEBROWSER_OIDC_CLIENT_ID=${FILEBROWSER__OIDC_CLIENT_ID}
      - FILEBROWSER_OIDC_CLIENT_SECRET=${FILEBROWSER__OIDC_CLIENT_SECRET}
    networks:
      - external
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.filebrowser.rule=Host(`files.${DOMAINNAME}`)"
      - "traefik.http.routers.filebrowser.middlewares=authelia@docker"        
      - "traefik.http.services.filebrowser.loadbalancer.server.port=80" 
    volumes:
      - ${DATADIR}/filebrowser:/srv # Do not use a root "/" directory or include the "/var" folder
      - ${VOLDIR}/filebrowser:${FILEBROWSER__DATABASE_PATH}  # Do not use a root "/" directory or include the "/var" folder