services:
  authentik:
    container_name: authentik-server
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}
    command: server
    restart: unless-stopped
    depends_on:
      traefik:
        condition: service_started
        restart: false
      authentik-worker:
        condition: service_started
        restart: false
    logging:
      options:
        max-size: 10m                
    env_file:
      - .env
    secrets:
      - authentik_secret_key
      - authentik_pg_password
      - smtp_password
    networks:
      - internal
      - external
    labels:
      - "traefik.enable=true"       
      - "traefik.http.routers.authentik.rule=Host(`auth.$DOMAINNAME`)"      
      - "traefik.http.services.authentik.loadbalancer.server.port=9000" 
      - "deunhealth.restart.on.unhealthy=true"     

  authentik-worker:
    container_name: authentik-worker
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}
    command: worker
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_started
        restart: false
      socket-proxy:
        condition: service_healthy  
        restart: false
    logging:
      options:
        max-size: 10m    
    env_file:
      - .env
    secrets:
      - authentik_secret_key
      - authentik_pg_password
      - smtp_password
    networks:
      - internal
      - socket_proxy
    labels: 
      - "deunhealth.restart.on.unhealthy=true"