services:
  linkwarden:
    container_name: linkwarden
    image: ghcr.io/linkwarden/linkwarden:latest # comment to build from source
    restart: always
    secrets:
      - smtp_password
      - linkwarden_nextauth_secret
      - linkwarden_oidc_clientid
      - linkwarden_oidc_secret
      - linkwarden_pg_password
    env_file: 
      - .env
    environment:
      - DATABASE_URL=postgresql://${DATABASE_NAME}:${DATABASE_PASSWORD_FILE}@${DATABASE_SERVER}:${DATABASE_PORT}/${DATABASE_NAME}
    volumes:
      - ${VOLDIR}/linkwarden:/data/data
    networks: 
      - internal
      - external
    labels:
      - "traefik.enable=true"       
      - "traefik.http.routers.linkwarden.rule=Host(`bookmark.$DOMAINNAME`)"      
      - "traefik.http.services.linkwarden.loadbalancer.server.port=3000"      