services:
  linkwarden:
    container_name: linkwarden
    image: ghcr.io/linkwarden/linkwarden:latest # comment to build from source
    restart: always
    env_file: 
      - .env
    #environment:
    #  - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres
    volumes:
      - ${VOLDIR}/linkwarden:/data/data
    networks: 
      - internal
      - external
    labels:
      - "traefik.enable=true"       
      - "traefik.http.routers.linkwarden.rule=Host(`bookmark.$DOMAINNAME`)"      
      - "traefik.http.services.linkwarden.loadbalancer.server.port=3000"      