services:
  deunhealth:
    container_name: deunhealth
    image: ${DEUNHEALTH__IMAGE}:${DEUNHEALTH__VERSION}
    #profiles: ["${DEUNHEALTH_PROFILE:-infrastructure}"]
    restart: unless-stopped
    depends_on:
      socket-proxy:
        condition: service_healthy
        restart: false
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
    environment:
      TZ: ${TZ}
      DOCKER_HOST: ${DOCKER_HOST}
      LOG_LEVEL: ${LOG_LEVEL}
    networks:
      - internal
      - socket_proxy
    labels:
      - "deunhealth.restart.on.unhealthy=false"
      - "traefik.enable=false"