name: immich
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    restart: always
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_started
        restart: false
      traefik:
        condition: service_started
        restart: false
      postgres:
        condition: service_started
        restart: false
    logging:
      options:
        max-size: 10m
      
    networks:
      - external
      - internal
    labels:
      - "traefik.enable=true"       
      - "traefik.http.routers.immich.rule=Host(`photos.$DOMAINNAME`)"      
      - "traefik.http.services.immich.loadbalancer.server.port=2283"  
      - "deunhealth.restart.on.unhealthy=true"
      - "com.centurylinklabs.watchtower.monitor-only=true"
    volumes:
      - ${UPLOAD_LOCATION}:/data
      - /etc/localtime:/etc/localtime:ro
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-openvino
    restart: always
    logging:
      options:
        max-size: 10m
    env_file:
      - .env
    networks:
      - internal
    labels:
      - "deunhealth.restart.on.unhealthy=true"
      - "com.centurylinklabs.watchtower.monitor-only=true"
    volumes:
      - ${VOLDIR}/immich/model-cache:/cache
    healthcheck:
      disable: false
  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:8-bookworm@sha256:a137a2b60aca1a75130022d6bb96af423fefae4eb55faf395732db3544803280
    restart: always
    logging:
      options:
        max-size: 10m
    networks:
      - internal
    labels:
      - "deunhealth.restart.on.unhealthy=true"
      - "com.centurylinklabs.watchtower.monitor-only=true"
    volumes:
      - ${VOLDIR}/immich/redis:/data
    healthcheck:
      test: redis-cli ping || exit 1