services:
  immich-server:
    container_name: immich_server
    image: ${IMMICH__IMAGE}:${IMMICH__VERSION}
    restart: always
    depends_on:
      redis:
        condition: service_started
        restart: false
      traefik:
        condition: service_started
        restart: false
      postgres:
        condition: service_started
        restart: false
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"    
    secrets:
      - immich_pg_password
    environment:
      - TZ="${TZ}"
      - PUID="${PUID}"
      - PGID="${PGID}" 
      - UPLOAD_LOCATION=${IMMICH__UPLOAD_LOCATION}
      - DB_HOSTNAME=${POSTGRESQL__HOST}
      - DB_PORT=${POSTGRESQL__PORT}
      - DB_USERNAME=${IMMICH__DB_USERNAME}
      - DB_DATABASE_NAME=${IMMICH__DB_DATABASE_NAME}
      - DB_PASSWORD_FILE=${IMMICH__DB_PASSWORD_FILE}
    networks:
      - external
      - internal
    labels:
      - "traefik.enable=true"       
      - "traefik.http.routers.immich.rule=Host(`photos.$DOMAINNAME`)"
      - "traefik.http.routers.immich.middlewares=authelia@docker"        
      - "traefik.http.services.immich.loadbalancer.server.port=2283"  
      - "deunhealth.restart.on.unhealthy=true"
    volumes:
      - ${IMMICH__UPLOAD_LOCATION}:/data
      - /etc/localtime:/etc/localtime:ro
    devices:
      - "/dev/dri:/dev/dri" 

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ${IMMICH_ML__IMAGE}:${IMMICH_ML__VERSION}
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
    networks:
      - internal
    labels:
      - "deunhealth.restart.on.unhealthy=true"
    volumes:
      - ${VOLDIR}/immich/model-cache:/cache