services:
  couchserver:
    container_name: couchdb
    image: couchdb
    restart: always
    depends_on:
      traefik:
        condition: service_started
        restart: false
    logging:
      options:
        max-size: 10m
    networks:
      - internal
    labels:
      - "traefik.enable=true"       
      - "traefik.http.routers.couchserver.rule=Host(`couch.int.$DOMAINNAME`)"      
      - "traefik.http.services.couchserver.loadbalancer.server.port=5984"  
      - "deunhealth.restart.on.unhealthy=true"
    volumes:
      - ${VOLDIR}/couch/dbdata:/opt/couchdb/data
      - ${VOLDIR}/couch/config:/opt/couchdb/etc