services:
  couchserver:
    container_name: couchdb
    image: ${COUCHDB__IMAGE}:${COUCHDB__VERSION}
    restart: always
    security_opt:
    - no-new-privileges:true
    - apparmor:unconfined
    #cap_drop:
    #  - ALL
    #read_only: true
    tmpfs:
    - /tmp:rw,noexec,nosuid
    depends_on:
      traefik:
        condition: service_started
        restart: false
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
    environment:
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: ${PGID}
    networks:
    - internal
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.couchserver.rule=Host(`couch.$DOMAINNAME`)"
    - "traefik.http.services.couchserver.loadbalancer.server.port=5984"
    - "deunhealth.restart.on.unhealthy=true"
    volumes:
    - ${VOLDIR}/couch/dbdata:/opt/couchdb/data
    - ${VOLDIR}/couch/config:/opt/couchdb/etc
