services:
  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server:latest
    restart: unless-stopped
    depends_on:
      traefik:
        condition: service_started
        restart: false
      postgres:
        condition: service_started
        restart: false
    logging:
      options:
        max-size: 10m
    env_file: 
      - .env
    secrets:
      - vaultwarden_pg_url
      - smtp_password
    networks:
      - external
      - internal
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vaultwarden-https.rule=Host(`vw.$DOMAINNAME`)"
      - "traefik.http.services.vaultwarden.loadbalancer.server.port=80"
      
      - "deunhealth.restart.on.unhealthy=true"
      - "com.centurylinklabs.watchtower.monitor-only=true"
    volumes:
      - ${VOLDIR}/vaultwarden/:/data/    
