services:
  booklore:
    image: ${BOOKLORE__IMAGE}:${BOOKLORE__VERSION}
    container_name: booklore
    restart: unless-stopped
    depends_on:
      traefik:
        condition: service_started
        restart: false
      mariadb:
        condition: service_started
        restart: false
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
    environment:
      - UMASK="000"
      - TZ="${TZ}"
      - PUID="${PUID}"
      - PGID="${PGID}"      
      - DATABASE_URL=${BOOKLORE__DB_URL}
      - DATABASE_USERNAME=${BOOKLORE__DB_USER}
      - DATABASE_PASSWORD=${BOOKLORE__DB_PASSWORD}
      - BOOKLORE_PORT=${BOOKLORE__PORT}   
    volumes:
      - ${VOLDIR}/booklore/data:/app/data
      - ${DATADIR}/torrents/:/books
      - ${VOLDIR}/booklore/:/bookdrop
    networks:
      - external
      - internal
    labels:
      - "traefik.enable=true"       
      - "traefik.http.routers.booklore.rule=Host(`booklore.$DOMAINNAME`)"      
      - "traefik.http.services.booklore.loadbalancer.server.port=${BOOKLORE__PORT}"
      - "deunhealth.restart.on.unhealthy=true"
  
  mariadb:
    container_name: booklore-mariadb
    image: ${MARIADB__IMAGE}:${MARIADB__VERSION}
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - MYSQL_USER=${BOOKLORE__DB_USER}
      - MYSQL_DATABASE=${BOOKLORE__DB_NAME}
      - MYSQL_PASSWORD=${BOOKLORE__DB_PASSWORD}      
      - MYSQL_ROOT_PASSWORD=${BOOKLORE__ROOT_PASSWORD}   
    volumes:
      - ${VOLDIR}/booklore/mariadb/:/config
    networks:
      - internal
    labels:      
      - "deunhealth.restart.on.unhealthy=true"