services:
  booklore:
    image: booklore/booklore:latest    
    container_name: booklore
    restart: unless-stopped
    env_file: .env
    environment:
      # Default
      - TZ="${TZ:-Europe/London}"
      - PUID="${PUID:-1000}"
      - PGID="${PGID:-1000}"
      - UMASK="000"
      #image
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_USERNAME=${DB_USER}
      - DATABASE_PASSWORD=${DB_PASSWORD}
      - BOOKLORE_PORT=6060
      
    volumes:
      - ${VOLDIR}/booklore/data:/app/data
      - ${DATADIR}/torrents/:/books
      - ${VOLDIR}/booklore/:/bookdrop
    networks:
      - external
      - internal
    labels:
      - "traefik.enable=true"       
      - "traefik.http.routers.booklore.rule=Host(`booklore.$DOMAINNAME`)"      
      - "traefik.http.services.booklore.loadbalancer.server.port=6060"
  
  mariadb:
    image: lscr.io/linuxserver/mariadb:11.4.5
    container_name: booklore-mariadb
    restart: unless-stopped
    env_file: .env
    environment:
      - PUID=${DB_USER_ID}
      - PGID=${DB_GROUP_ID}
      - TZ=${TZ}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - ${VOLDIR}/booklore/mariadb/:/config
    networks:
      - internal

networks:
  external:
    external: true
  internal: 
    external: true
