services:
  flaresolverr:
    container_name: flaresolverr
    image: ghcr.io/flaresolverr/flaresolverr:latest
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
    environment:
      - TZ=${TZ}
      - PROXY_URL="http://vpn:8888"
    labels:
      - "deunhealth.restart.on.unhealthy=true"
    networks:
      - external
    volumes:
      - ${VOLDIR}/prowlarr/flaresolverr:/config
  
  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:latest
    restart: unless-stopped
    depends_on:
      traefik:
        condition: service_started
        restart: false
    logging:
      options:
        max-size: 10m
    networks:
      - external
    labels:
      - "traefik.enable=true"       
      - "traefik.http.routers.prowlarr.rule=Host(`prowlarr.int.${DOMAINNAME}`)"      
      - "traefik.http.services.prowlarr.loadbalancer.server.port=9696"
      - "deunhealth.restart.on.unhealthy=true"
    volumes:
      - ${VOLDIR}/prowlarr/:/config