services:
  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/London
    #ports:
    #  - 11036:8191
    volumes:
      - ${VOLUME_DIRECTORY}/flaresolver:/config
    networks:
      - internal
      - arr
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    volumes:
      - ${VOLUME_DIRECTORY}/prowlarr/:/config
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - internal
      - arr
    labels:
      - "traefik.enable=true"       
      - "traefik.http.routers.prowlarr.rule=Host(`prowlarr.int.$DOMAIN`)"      
      - "traefik.http.services.prowlarr.loadbalancer.server.port=9696"      

networks:
  internal:
    external: true
  arr:
    external: true