services:
  flaresolverr:
    container_name: flaresolverr
    image: ghcr.io/flaresolverr/flaresolverr:latest
    restart: unless-stopped
    environment:
      - TZ=${TZ}
    networks:
      - internal   
    volumes:
      - ${VOLDIR}/prowlarr/flaresolver:/config
  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:latest
    restart: unless-stopped
    networks:
      - internal
    labels:
      - "traefik.enable=true"       
      - "traefik.http.routers.prowlarr.rule=Host(`prowlarr.int.${DOMAINNAME}`)"      
      - "traefik.http.services.prowlarr.loadbalancer.server.port=9696"   
    volumes:
      - ${VOLDIR}/prowlarr/:/config
