services:
  flaresolverr:
    container_name: flaresolverr
    image: ${FLARESOLVERR__IMAGE}:${FLARESOLVERR__VERSION}
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
    environment:
      - TZ=${TZ}
      - PROXY_URL="${VPN__PROXY_URL}"
    networks:
      - external
    labels:
      - "deunhealth.restart.on.unhealthy=true"
    volumes:
      - ${VOLDIR}/prowlarr/flaresolverr:/config
  
  prowlarr:
    container_name: prowlarr
    image: ${PROWLARR__IMAGE}:${PROWLARR__VERSION}
    restart: unless-stopped
    depends_on:
      traefik:
        condition: service_started
        restart: false
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
    networks:
      - external
    labels:
      - "traefik.enable=true"       
      - "traefik.http.routers.prowlarr.rule=Host(`prowlarr.int.${DOMAINNAME}`)"
      - "traefik.http.routers.prowlarr.middlewares=authelia@docker"      
      - "traefik.http.services.prowlarr.loadbalancer.server.port=9696"
      - "deunhealth.restart.on.unhealthy=true"
    volumes:
      - ${VOLDIR}/prowlarr/:/config