services:
  watchtower: # https://containrrr.dev/watchtower/usage-overview/
    container_name: watchtower
    image: ${WATCHTOWER__IMAGE}:${WATCHTOWER__VERSION}
    #profiles: ["${WATCHTOWER_PROFILE:-infrastructure}"]
    restart: unless-stopped
    networks:
      - external
      - internal
      - socket_proxy
    depends_on:
      socket-proxy:
        condition: service_started
        restart: true
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
    environment:
      TZ: "${TZ}"
      DOCKER_HOST: "${DOCKER_HOST}"
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_INCLUDE_STOPPED: "true"
      WATCHTOWER_LABEL_TAKE_PRECEDENCE: "true"
      WATCHTOWER_USE_COMPOSE_DEPENDS_ON: "false"
      WATCHTOWER_POLL_INTERVAL: "3600"            
      WATCHTOWER_REMOVE_VOLUMES: "true"
      WATCHTOWER_TIMEOUT: "30s"
    labels:
      - "com.centurylinklabs.watchtower.monitor-only=true"
      - "deunhealth.restart.on.unhealthy=true"
      - "traefik.enable=false"