services:
  vpn:
    container_name: vpn
    image: ${VPN__IMAGE}:${VPN__VERSION}
    #profiles: ["${VPN_PROFILE:-network}"]
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
    cap_add:
      - "NET_ADMIN"
    cpu_shares: 2048  # Ensure this always gets what is needed
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    secrets:
      - wireguard_private_key
      - wireguard_preshared_key
      - wireguard_addresses
    environment:
      # Default
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      # Image
      - WIREGUARD_PRIVATE_KEY_FILE=${WIREGUARD_PRIVATE_KEY_FILE}
      - WIREGUARD_PRESHARED_KEY_FILE=${WIREGUARD_PRESHARED_KEY_FILE}
      - WIREGUARD_ADDRESSES_FILE=${WIREGUARD_ADDRESSES_FILE}
      - VPN_SERVICE_PROVIDER="${VPN__SERVICE_PROVIDER}"
      - VPN_TYPE="${VPN__TYPE}" 
      - SERVER_COUNTRIES="${VPN__SERVER_COUNTRIES}"
      - FIREWALL_VPN_INPUT_PORTS="${TORRENTING_PORT}"
      - FIREWALL_OUTBOUND_SUBNETS="${VPN__EXTERNAL_SUBNETS}" #? not sure if this is needed, but it doesn't hurt to be explicit about it  
      - HTTPPROXY="on"
    ports:
      - 8080:8080 # qbittorrent webui      
      - 38534:38534 # qbittorrent
      - 8888:8888 # HTTP proxy
    networks:
      - external
      - internal
    labels:
      - "deunhealth.restart.on.unhealthy=true"
      - "traefik.enable=false"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
    devices:
      - "/dev/net/tun:/dev/net/tun"