services: 
  audiobookshelf:
    container_name: audiobookshelf
    image: ghcr.io/advplyr/audiobookshelf:latest
    environment:
      # Default
      TZ: "${TZ:-Europe/London}"
      PUID: "${PUID:-1000}"
      PGID: "${PGID:-1000}"
      UMASK: "000"
    volumes:
      - ${DATADIR}/torrents:/audiobooks
      - ${VOLDIR}/abs/config:/config
      - ${VOLDIR}/abs/meta:/metadata
      #- </path/to/podcasts>:/podcasts
    networks:
      - external    
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.audiobookshelf.rule=Host(`audiobookshelf.$DOMAINNAME`)"
      - "traefik.http.services.audiobookshelf.loadbalancer.server.port=80"