services:
  qbittorrent:
    container_name: qbittorrent
    image: ${QBITTORRENT__IMAGE}:${QBITTORRENT__VERSION}
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    #   - apparmor:unconfined
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    #read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid
    depends_on:
      traefik:
        condition: service_started
        restart: false
      vpn:
        condition: service_healthy
        restart: false
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - WEBUI_PORT=${WEBUI_PORT}
      - TORRENTING_PORT=${TORRENTING_PORT}
    network_mode: "container:vpn"
    labels:
      - "traefik.enable=true"       
      - "traefik.http.routers.qbittorrent.rule=Host(`q.int.$DOMAINNAME`)"      
      - "traefik.http.routers.qbittorrent.middlewares=authelia@docker"
      - "traefik.http.services.qbittorrent.loadbalancer.server.port=${WEBUI_PORT}"
      - "deunhealth.restart.on.unhealthy=true"
    volumes:
      - $VOLDIR/qbittorrent:/config:rw
      - $DATADIR/torrents/downloads:/downloads:rw

    healthcheck:
      start_period: "30s"
      test: "curl --connect-timeout 5 --silent --show-error --fail http://localhost:8080/"