services:  
  traefik:
    image: traefik:3.6.10
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    env_file:
      - .env
    environment:
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
      - CF_API_EMAIL=${EMAIL}
    networks:
      - external
      - internal
    ports:
      - 80:80
      - 443:443
      #- 8080:8080
    command:
      #API + Dash
      - "--api.insecure=true"
      - "--api.dashboard=true"   

      # Attach the static configuration tls.yaml file that contains the tls configuration settings 
      #- "--providers.file.filename=/dynamic/tls.yaml"
      #- "--providers.file.watch=true"
      
      - "--serversTransport.insecureSkipVerify=true"
      # EntryPoints
      - "--entryPoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--entryPoints.web.http.redirections.entryPoint.to=websecure"
      - "--entryPoints.web.http.redirections.entryPoint.scheme=https"  

      - "--entryPoints.websecure.address=:443"
      - "--entryPoints.websecure.http.tls=true"
      - "--entrypoints.websecure.http.tls.certresolver=letsencrypt"
      - "--entryPoints.websecure.http3=true"
      #providers
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      #???? - "--providers.docker.network=proxy"      
   
      #certs 
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge=true"

      - "--certificatesresolvers.letsencrypt.acme.dnschallenge.propagation.delayBeforeChecks=10"
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge.resolvers=8.8.8.8:53"      
      - "--certificatesresolvers.letsencrypt.acme.email=${EMAIL}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/etc/traefik/acme.json"

      - "--entryPoints.websecure.http.tls.domains[0].main=$DOMAIN"
      - "--entryPoints.websecure.http.tls.domains[0].sans=*.$DOMAIN"

            
      # Observability 
      - "--log.level=INFO"
      - "--ping=true"
      #- "--accesslog=true"
      #- "--metrics.prometheus=true"
            
    # Traefik Dynamic configuration via Docker labels
    labels:
      # Enable self‑routing
      - traefik.enable=true
      - traefik.http.routers.api.rule=Host(`traefik.int.${DOMAIN}`)
      - traefik.http.routers.api.service=api@internal
      - traefik.http.services.api.loadbalancer.server.port=8080

      #  Basic‑auth middleware
      - traefik.http.middlewares.api-auth.basicauth.users=sabrina:$$apr1$$kHonGrZB$$pssgJmXUjdGEJznac883K0 
      - traefik.http.routers.api.middlewares=api-auth@docker      

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  
      - ./config:/etc/traefik

    healthcheck:
      test: wget --quiet --tries=1 --spider http://127.0.0.1:8080/ping || exit 1
      interval: 5s
      timeout: 1s
      retries: 3
      start_period: 10s


  # authentik-proxy:
  #   image: ghcr.io/goauthentik/proxy:2026.2.0
  #   networks:
  #     - internal
  #   ports:
  #     - 9000:9000
  #     - 9443:9443    
  #   environment:
  #     AUTHENTIK_HOST: https://auth.lilyvitta.com
  #     AUTHENTIK_INSECURE: "false"
  #     AUTHENTIK_TOKEN: token-generated-by-authentik
  #     # Starting with 2021.9, you can optionally set this too
  #     # when authentik_host for internal communication doesn't match the public URL
  #     # AUTHENTIK_HOST_BROWSER: https://external-domain.tld
  #   labels:
  #     traefik.enable: true
  #     traefik.port: 9000
  #     traefik.http.routers.authentik.rule: Host(`${DOMAIN}`) && PathPrefix(`/outpost.goauthentik.io/`)
  #     # `authentik-proxy` refers to the service name in the compose file.
  #     traefik.http.middlewares.authentik.forwardauth.address: http://authentik-proxy:9000/outpost.goauthentik.io/auth/traefik
  #     traefik.http.middlewares.authentik.forwardauth.trustForwardHeader: true
  #     traefik.http.middlewares.authentik.forwardauth.authResponseHeaders: X-authentik-username,X-authentik-groups,X-authentik-entitlements,X-authentik-email,X-authentik-name,X-authentik-uid,X-authentik-jwt,X-authentik-meta-jwks,X-authentik-meta-outpost,X-authentik-meta-provider,X-authentik-meta-app,X-authentik-meta-version
  #   restart: unless-stopped




volumes:
  acme:
  traefik:

networks:
  internal:
    name: internal
    external: true
  external:
    name: external
    external: true
  host:
    name: external
    external: true
