services:
  pgadmin:
    container_name: postgres-web
    image: dpage/pgadmin4
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_started
        restart: false
      traefik:
        condition: service_started
        restart: false
    logging:
          driver: "json-file"
          options:
            max-size: "1m"
            max-file: "3"
    user: '0:0' ###ermmmm
    environment:
      - TZ=${TZ}
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN__DEFAULT_EMAIL}
    networks:
      - internal
    labels:
      - "traefik.enable=true"       
      - "traefik.http.routers.pgadmin.rule=Host(`pg.int.$DOMAINNAME`)"      
      - "traefik.http.services.pgadmin.loadbalancer.server.port=80"
      - "deunhealth.restart.on.unhealthy=true"
    volumes:
      - ${VOLDIR}/pgadmin:/var/lib/pgadmin